### ISSUE TITLE
Problems updating data from an external database in SQLITE in Flutter.

### ISSUE THREAD

**Issue by fabiomicheldossantos** [tekartik/sqflite#1116]
I have an app that uses an external database, which has 7 tables. I frequently update the content of three tables (videos_chapters, videos_theme and references) and, after that, I copy the updated database to the app's assets folder, overwriting the previous file. I want that when I upload an app update to Google Play, the content of only these three tables is updated on the user's phone, but this is not happening. When the user installs the update, the records remain the same. I'm using the sqflite package. Is there a solution for this?

**Comment by fabiomicheldossantos** [comment]
I apologize for not being so clear. I will try to explain better now by simplifying the problem. I released an app on Google Play that aims to allow the user to read a book. This app uses a database that has three tables. The database is located in the assets folder and I use the same code presented in the link you sent me. Table "A" has 5,000 records that correspond to the paragraphs of the book. Table "B" is initially empty and its purpose is to record the color of the markings that the user makes in a paragraph of the book. Table "C" contains links related to the themes of each chapter. I often copy the database file to my desktop, manually insert new records into table "C" using the "DB Browser for SQLite" software, and then copy my database back to the assets folder of my project. Last week, after following this procedure, I noticed that when I uploaded a new app update to Google Play, the new records I inserted in table "C" were not displayed to users who updated the app. Is it possible to make it so that when I upload an app update to Google Play, only table "C" is updated on the user's device, displaying the new records I inserted? I searched on Google to see if I could find a solution, but I didn't find one. I apologize if I wasn't clear enough again.

`Future<Database> iniciaBancoDeDados() async {
    final caminhoBancoDeDados = await getDatabasesPath();
    final path = join(caminhoBancoDeDados, "ide.db");
    bool exist = await databaseExists(path);

    if (exist) {
      await openDatabase(path);
    } else {
      try {
        await Directory(dirname(path)).create(recursive: true);
      } catch (_) {}

      final data = await rootBundle.load(
        join("assets", "ide.db"),
      );

      List<int> bytes = data.buffer.asUint8List(
        data.offsetInBytes,
        data.lengthInBytes,
      );

      await File(path).writeAsBytes(bytes, flush: true);
    }

    final db = await openDatabase(path);
    return db;
  }`

**Comment by alextekartik** [comment]
Indeed if the database has been copied once, it exists so it won't be read again from the asset folder even after a google play update (since the database still exists!), I'll propose a solution below.
Regarding updating only a single table is more complex, I suggest having 2 databases:
- one read-only (typically table A and C in your case)
- one user-writable (table B in your case)

My solution is only for the read-only database, the user one does not have to be in the assets.

So the simple solution is to uses a versioning system using an incremental number. An asset version file stores this number. When the app starts,
it checks the version file currently existing on the file system, compare it to the one in the assets and decide
to copy the asset (the db and the version file) or not.

Let's assume that you have a version file named `db_version_num.txt` in your assets folder.
The content of the file is a single line with the version number.

`db_version_num.txt`
```txt
1
```

along with the database file `my_asset_database.db`

You could have the following code to copy the asset database only if the version number is different:
```dart
/// Copy the asset database if needed and open it.
///
/// It uses an external version file to keep track of the asset version.
Future<Database> copyIfNeededAndOpenAssetDatabase(
    {required String databasesPath,
      required String versionNumFilename,
      required String dbFilename}) async {
  var dbPath = join(databasesPath, dbFilename);

  // First check the currently installed version
  var versionNumFile = File(join(databasesPath, versionNumFilename));
  var existingVersionNum = 0;
  if (versionNumFile.existsSync()) {
    existingVersionNum = int.parse(await versionNumFile.readAsString());
  }

  // Read the asset version
  var assetVersionNum = int.parse(
      (await rootBundle.loadString(url.join('assets', versionNumFilename))).trim());

  // Compare them.
  print('existing/asset: $existingVersionNum/$assetVersionNum');

  // If needed, copy the asset database
  if (existingVersionNum < assetVersionNum) {
    print('copying new version $assetVersionNum');
    // Make sure the parent directory exists
    try {
      await Directory(databasesPath).create(recursive: true);
    } catch (_) {}

    // Copy from asset
    var data = await rootBundle.load(url.join('assets', dbFilename));
    var bytes = Uint8List.sublistView(data);

    // Write and flush the database bytes written
    await File(dbPath).writeAsBytes(bytes, flush: true);
    // Write and flush the version file
    await versionNumFile.writeAsString('$assetVersionNum', flush: true);
  }

  var db = await openDatabase(dbPath);
  return db;
}
```

**Comment by fabiomicheldossantos** [comment]
@alextekartik, thank you for your reply. I managed to solve it. God bless you always!
