### ISSUE TITLE
[windows] issue with release

### ISSUE THREAD

**Issue by mjafartp** [tekartik/sqflite#760]
With the latest update, it not working in release mode or changing the application location.
The error because of getting Database path with the new implementation 

`FileSystemException: Cannot open file, path = '.dart_tool\\package_config.json' (OS Error: The system cannot find the path specified.\r\n, errno = 3), stack:#0      _File.throwIfError (dart:io/file_impl.dart:635)\n#1      _File.openSync (dart:io/file_impl.dart:479)\n#2      _File.readAsBytesSync (dart:io/file_impl.dart:539)\n#3      _File.readAsStringSync (dart:io/file_impl.dart:584)\n#4      pathGetJson (package:sqflite_common_ffi/src/windows/setup_impl.dart:9)\n#5      pathGetPackageConfigMap (package:sqflite_common_ffi/src/windows/setup_impl.dart:20)\n#6      findPackageLibPath (package:sqflite_common_ffi/src/windows/setup.dart:47)\n#7      findWindowsDllPath (package:sqflite_common_ffi/src/windows/setup.dart:59)\n#8      windowsInit (package:sqflite_common_ffi/src/windows/setup.dart:27)\n#9      sqfliteFfiInit (package:sqflite_common_ffi/src/sqflite_ffi_io.dart:60)\n#10     SqLite.createDatabase`

**Comment by alextekartik** [comment]
Thanks for report, indeed missing handling such a regular scenario. I'm fixing the issue

**Comment by alextekartik** [comment]
Fixed in sqflite_common_ffi 2.1.0+2

**Comment by SteveCruise** [comment]
@alextekartik Still not fixed. I'm using `sqflite_common_ffi: ^2.1.0+2`, when in release and install as msix, it can't run because it hasn't `.dart_tool/package_config.json` file in **running** directory.

**Comment by alextekartik** [comment]
@SteveCruise Did you bundle sqlite3.dll in your msix - that is a needed step - ? Do you get the same error logs than above (weird since this should be fixed) ? sqfliteFFiInit is just a refenced implementation. Otherwise you can setup your own loader (such as looking in the same directoy than your executable) as described in the sqlite3 package (https://pub.dev/packages/sqlite3)

**Comment by SteveCruise** [comment]
Great! I fixed it by add `sqlite3_flutter_libs` in `pubspec.yaml`. The windows release auto create `.dart_tool` directory.
